apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - namespace.yaml
  - dragonfly.yaml
  - ../../base
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: course-app
